version: "2"

services:
  api01: &api
    build: .
    hostname: api01
    restart: unless-stopped
    networks:
      - default
    environment:
      - PORT=3000
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "60MB"

  api02:
    <<: *api
    hostname: api2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha-2024
