version: "3.5"

services:
  api01: &api
    build: .
    hostname: api01
    restart: unless-stopped
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  api02:
    <<: *api
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    hostname: api2

  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile.lb
    network_mode: host
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "100MB"
